name: assesment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.2
  hooks_riverpod: ^2.5.1
  retrofit: ^4.4.1
  riverpod_annotation: ^2.3.5
  socket_io_client: ^2.0.3+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  analyzer: ^6.4.1
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
